// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {lip} from '../models';
import {compatibility} from '../models';
import {backend} from '../models';
import {server} from '../models';
import {addons} from '../models';

export function AddAllowlistPlayer(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function AddXboxAccountAsOp(arg1:string):Promise<void>;

export function AnalyzeAddon(arg1:string):Promise<models.AddonAnalysisResult>;

export function ApplyComponentUpdate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<lip.CommandResult>;

export function AssignAddonToWorld(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<number>):Promise<void>;

export function AutomateServerSetup(arg1:string):Promise<void>;

export function BanPlayer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function BringToFront():Promise<void>;

export function CheckAllUpdates(arg1:string):Promise<models.UpdateCheckReport>;

export function CheckCompatibility(arg1:string):Promise<compatibility.FullCompatibilityReport>;

export function CheckCurseForgeUpdates():Promise<models.CurseForgeUpdateReport>;

export function CheckLipStatus(arg1:string):Promise<models.LipStatus>;

export function CheckMarketplaceUpdates():Promise<models.MarketplaceUpdateReport>;

export function CheckServerFiles(arg1:string):Promise<backend.ServerSetupStatus>;

export function CheckVCRedist():Promise<boolean>;

export function ClearActivityLogs():Promise<void>;

export function ClearXboxAccount():Promise<void>;

export function CreateBackup(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Backup>;

export function CreateServer(arg1:server.CreateServerOptions):Promise<models.Server>;

export function CreateWorld(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateWorldWithOptions(arg1:string,arg2:models.WorldCreateOptions):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeleteWorld(arg1:string,arg2:string):Promise<void>;

export function DeopPlayer(arg1:string,arg2:string):Promise<void>;

export function DetectXboxAccount():Promise<models.XboxAccount>;

export function DisableMod(arg1:string):Promise<void>;

export function DownloadMarketplaceItem(arg1:string):Promise<string>;

export function EnableLoopbackExemption():Promise<string>;

export function EnableMod(arg1:string):Promise<void>;

export function ExportAddon(arg1:string,arg2:string):Promise<string>;

export function FixNetworkAndJoinIssues(arg1:string):Promise<models.JoinHealthReport>;

export function GetActiveServer():Promise<models.Server>;

export function GetActivityLogs():Promise<Array<string>>;

export function GetAppSettings():Promise<string>;

export function GetBedrinthPackages():Promise<Array<models.BedrinthPackage>>;

export function GetConsoleLogs(arg1:string):Promise<Array<string>>;

export function GetCurseForgeCatalog(arg1:string,arg2:string):Promise<Array<models.CurseForgeCatalogItem>>;

export function GetCurseForgeCatalogLive(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<models.CurseForgeCatalogResponse>;

export function GetDefaultServerLocation(arg1:string):Promise<string>;

export function GetExtensionsCatalog():Promise<Array<models.ExtensionManifest>>;

export function GetExtensionsOverview(arg1:string,arg2:string):Promise<models.ExtensionsOverview>;

export function GetModConfig(arg1:string):Promise<Record<string, any>>;

export function GetNextAvailablePort():Promise<number>;

export function GetPlayersOverview(arg1:string):Promise<models.PlayersOverview>;

export function GetPreference(arg1:string,arg2:string):Promise<string>;

export function GetServer(arg1:string):Promise<models.Server>;

export function GetServerIPs():Promise<Record<string, string>>;

export function GetServerMemoryLimit(arg1:string):Promise<number>;

export function GetServerMetrics(arg1:string):Promise<models.ServerMetrics>;

export function GetServerProperties(arg1:string):Promise<Record<string, string>>;

export function GetServerStatus(arg1:string):Promise<models.ServerStatus>;

export function GetServers():Promise<Array<models.Server>>;

export function GetToolCoinCatalog(arg1:string,arg2:string):Promise<Array<models.ToolCoinCatalogItem>>;

export function GetToolCoinCatalogLive(arg1:string,arg2:string,arg3:number,arg4:number):Promise<models.ToolCoinCatalogResponse>;

export function GetWorldOptions(arg1:string,arg2:string):Promise<models.WorldOptions>;

export function GetXboxAccount():Promise<models.XboxAccount>;

export function ImportServer(arg1:string):Promise<models.Server>;

export function ImportWorld(arg1:string,arg2:string):Promise<models.World>;

export function InspectImportFile(arg1:string):Promise<backend.UniversalImportResult>;

export function InstallAddon(arg1:string,arg2:string,arg3:addons.InstallOptions):Promise<addons.InstalledPackResult>;

export function InstallBedrinthPackage(arg1:string,arg2:string,arg3:string):Promise<lip.CommandResult>;

export function InstallCurseForgeCatalogItem(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InstallCurseForgeItemLive(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<void>;

export function InstallExtension(arg1:string):Promise<void>;

export function InstallLip():Promise<string>;

export function InstallLipPackage(arg1:string,arg2:string):Promise<lip.CommandResult>;

export function InstallToolCoinCatalogItem(arg1:string,arg2:string):Promise<void>;

export function InstallToolCoinPackage(arg1:string,arg2:string):Promise<void>;

export function InstallVCRedist():Promise<void>;

export function KickPlayer(arg1:string,arg2:string):Promise<void>;

export function LaunchToolCoin(arg1:string):Promise<void>;

export function ListAddons(arg1:string):Promise<Array<models.Addon>>;

export function ListBackups(arg1:string):Promise<Array<models.Backup>>;

export function ListMods(arg1:string):Promise<Array<models.Mod>>;

export function ListToolCoinDownloads(arg1:string):Promise<Array<models.ToolCoinPackage>>;

export function ListWorlds(arg1:string):Promise<Array<models.World>>;

export function OpPlayer(arg1:string,arg2:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenToolCoinDownloadsFolder(arg1:string):Promise<void>;

export function PollXboxDeviceAuth(arg1:string):Promise<models.XboxAccount>;

export function PruneBackups(arg1:string,arg2:number):Promise<number>;

export function PurgeDownloadedCache():Promise<void>;

export function RefreshCurseForgeCatalog():Promise<models.CurseForgeUpdateReport>;

export function RefreshMarketplaceDefinitions():Promise<models.MarketplaceUpdateReport>;

export function RemoveAllowlistPlayer(arg1:string,arg2:string):Promise<void>;

export function RemoveMod(arg1:string):Promise<void>;

export function ReorderWorldPacks(arg1:string,arg2:string,arg3:Array<models.WorldPackRecord>,arg4:Array<models.WorldPackRecord>):Promise<void>;

export function RescanServer(arg1:string):Promise<models.Server>;

export function RestartServer(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function SaveAppSettings(arg1:string):Promise<void>;

export function SaveModConfig(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SaveServerProperties(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SaveWorldOptions(arg1:string,arg2:string,arg3:models.WorldOptions):Promise<void>;

export function SaveXboxAccount(arg1:models.XboxAccount):Promise<void>;

export function ScanRecentCurseForgeDownloads():Promise<Array<models.CurseForgeDownloadItem>>;

export function SelectFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectFolderDialog():Promise<string>;

export function SendConsoleCommand(arg1:string,arg2:string):Promise<void>;

export function SetActiveServer(arg1:string):Promise<void>;

export function SetActiveWorld(arg1:string,arg2:string):Promise<void>;

export function SetExtensionEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetPlayerPermission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPreference(arg1:string,arg2:string):Promise<void>;

export function SetServerMemoryLimit(arg1:string,arg2:number):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StartXboxDeviceAuth():Promise<models.DeviceAuthResponse>;

export function StopServer(arg1:string):Promise<void>;

export function SyncBedrinthCatalog():Promise<number>;

export function ToggleAddonForWorld(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ToggleAllowlist(arg1:string,arg2:boolean):Promise<void>;

export function ToggleFullscreen():Promise<boolean>;

export function UnassignAddonFromWorld(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UnbanPlayer(arg1:string,arg2:string):Promise<void>;

export function UninstallAddon(arg1:string,arg2:string):Promise<void>;

export function UninstallBedrinthPackage(arg1:string,arg2:string):Promise<lip.CommandResult>;

export function UninstallExtension(arg1:string):Promise<void>;

export function UpdateLipPackage(arg1:string,arg2:string):Promise<lip.CommandResult>;

export function WipeEverything(arg1:boolean):Promise<void>;
