// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowlistPlayer(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['AddAllowlistPlayer'](arg1, arg2, arg3, arg4);
}

export function AddXboxAccountAsOp(arg1) {
  return window['go']['backend']['App']['AddXboxAccountAsOp'](arg1);
}

export function AnalyzeAddon(arg1) {
  return window['go']['backend']['App']['AnalyzeAddon'](arg1);
}

export function ApplyComponentUpdate(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ApplyComponentUpdate'](arg1, arg2, arg3, arg4);
}

export function AssignAddonToWorld(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['AssignAddonToWorld'](arg1, arg2, arg3, arg4, arg5);
}

export function AutomateServerSetup(arg1) {
  return window['go']['backend']['App']['AutomateServerSetup'](arg1);
}

export function BanPlayer(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['BanPlayer'](arg1, arg2, arg3, arg4);
}

export function BringToFront() {
  return window['go']['backend']['App']['BringToFront']();
}

export function CheckAllUpdates(arg1) {
  return window['go']['backend']['App']['CheckAllUpdates'](arg1);
}

export function CheckCompatibility(arg1) {
  return window['go']['backend']['App']['CheckCompatibility'](arg1);
}

export function CheckCurseForgeUpdates() {
  return window['go']['backend']['App']['CheckCurseForgeUpdates']();
}

export function CheckLipStatus(arg1) {
  return window['go']['backend']['App']['CheckLipStatus'](arg1);
}

export function CheckMarketplaceUpdates() {
  return window['go']['backend']['App']['CheckMarketplaceUpdates']();
}

export function CheckServerFiles(arg1) {
  return window['go']['backend']['App']['CheckServerFiles'](arg1);
}

export function CheckVCRedist() {
  return window['go']['backend']['App']['CheckVCRedist']();
}

export function ClearActivityLogs() {
  return window['go']['backend']['App']['ClearActivityLogs']();
}

export function ClearXboxAccount() {
  return window['go']['backend']['App']['ClearXboxAccount']();
}

export function CreateBackup(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateBackup'](arg1, arg2, arg3, arg4);
}

export function CreateServer(arg1) {
  return window['go']['backend']['App']['CreateServer'](arg1);
}

export function CreateWorld(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateWorld'](arg1, arg2, arg3);
}

export function CreateWorldWithOptions(arg1, arg2) {
  return window['go']['backend']['App']['CreateWorldWithOptions'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['backend']['App']['DeleteServer'](arg1);
}

export function DeleteWorld(arg1, arg2) {
  return window['go']['backend']['App']['DeleteWorld'](arg1, arg2);
}

export function DeopPlayer(arg1, arg2) {
  return window['go']['backend']['App']['DeopPlayer'](arg1, arg2);
}

export function DetectXboxAccount() {
  return window['go']['backend']['App']['DetectXboxAccount']();
}

export function DisableMod(arg1) {
  return window['go']['backend']['App']['DisableMod'](arg1);
}

export function DownloadMarketplaceItem(arg1) {
  return window['go']['backend']['App']['DownloadMarketplaceItem'](arg1);
}

export function EnableLoopbackExemption() {
  return window['go']['backend']['App']['EnableLoopbackExemption']();
}

export function EnableMod(arg1) {
  return window['go']['backend']['App']['EnableMod'](arg1);
}

export function ExportAddon(arg1, arg2) {
  return window['go']['backend']['App']['ExportAddon'](arg1, arg2);
}

export function FixNetworkAndJoinIssues(arg1) {
  return window['go']['backend']['App']['FixNetworkAndJoinIssues'](arg1);
}

export function GetActiveServer() {
  return window['go']['backend']['App']['GetActiveServer']();
}

export function GetActivityLogs() {
  return window['go']['backend']['App']['GetActivityLogs']();
}

export function GetAppSettings() {
  return window['go']['backend']['App']['GetAppSettings']();
}

export function GetBedrinthPackages() {
  return window['go']['backend']['App']['GetBedrinthPackages']();
}

export function GetConsoleLogs(arg1) {
  return window['go']['backend']['App']['GetConsoleLogs'](arg1);
}

export function GetCurseForgeCatalog(arg1, arg2) {
  return window['go']['backend']['App']['GetCurseForgeCatalog'](arg1, arg2);
}

export function GetCurseForgeCatalogLive(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['GetCurseForgeCatalogLive'](arg1, arg2, arg3, arg4, arg5);
}

export function GetDefaultServerLocation(arg1) {
  return window['go']['backend']['App']['GetDefaultServerLocation'](arg1);
}

export function GetExtensionsCatalog() {
  return window['go']['backend']['App']['GetExtensionsCatalog']();
}

export function GetExtensionsOverview(arg1, arg2) {
  return window['go']['backend']['App']['GetExtensionsOverview'](arg1, arg2);
}

export function GetModConfig(arg1) {
  return window['go']['backend']['App']['GetModConfig'](arg1);
}

export function GetNextAvailablePort() {
  return window['go']['backend']['App']['GetNextAvailablePort']();
}

export function GetPlayersOverview(arg1) {
  return window['go']['backend']['App']['GetPlayersOverview'](arg1);
}

export function GetPreference(arg1, arg2) {
  return window['go']['backend']['App']['GetPreference'](arg1, arg2);
}

export function GetServer(arg1) {
  return window['go']['backend']['App']['GetServer'](arg1);
}

export function GetServerIPs() {
  return window['go']['backend']['App']['GetServerIPs']();
}

export function GetServerMemoryLimit(arg1) {
  return window['go']['backend']['App']['GetServerMemoryLimit'](arg1);
}

export function GetServerMetrics(arg1) {
  return window['go']['backend']['App']['GetServerMetrics'](arg1);
}

export function GetServerProperties(arg1) {
  return window['go']['backend']['App']['GetServerProperties'](arg1);
}

export function GetServerStatus(arg1) {
  return window['go']['backend']['App']['GetServerStatus'](arg1);
}

export function GetServers() {
  return window['go']['backend']['App']['GetServers']();
}

export function GetToolCoinCatalog(arg1, arg2) {
  return window['go']['backend']['App']['GetToolCoinCatalog'](arg1, arg2);
}

export function GetToolCoinCatalogLive(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['GetToolCoinCatalogLive'](arg1, arg2, arg3, arg4);
}

export function GetWorldOptions(arg1, arg2) {
  return window['go']['backend']['App']['GetWorldOptions'](arg1, arg2);
}

export function GetXboxAccount() {
  return window['go']['backend']['App']['GetXboxAccount']();
}

export function ImportServer(arg1) {
  return window['go']['backend']['App']['ImportServer'](arg1);
}

export function ImportWorld(arg1, arg2) {
  return window['go']['backend']['App']['ImportWorld'](arg1, arg2);
}

export function InspectImportFile(arg1) {
  return window['go']['backend']['App']['InspectImportFile'](arg1);
}

export function InstallAddon(arg1, arg2, arg3) {
  return window['go']['backend']['App']['InstallAddon'](arg1, arg2, arg3);
}

export function InstallBedrinthPackage(arg1, arg2, arg3) {
  return window['go']['backend']['App']['InstallBedrinthPackage'](arg1, arg2, arg3);
}

export function InstallCurseForgeCatalogItem(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['InstallCurseForgeCatalogItem'](arg1, arg2, arg3, arg4);
}

export function InstallCurseForgeItemLive(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['InstallCurseForgeItemLive'](arg1, arg2, arg3, arg4, arg5);
}

export function InstallExtension(arg1) {
  return window['go']['backend']['App']['InstallExtension'](arg1);
}

export function InstallLip() {
  return window['go']['backend']['App']['InstallLip']();
}

export function InstallLipPackage(arg1, arg2) {
  return window['go']['backend']['App']['InstallLipPackage'](arg1, arg2);
}

export function InstallToolCoinCatalogItem(arg1, arg2) {
  return window['go']['backend']['App']['InstallToolCoinCatalogItem'](arg1, arg2);
}

export function InstallToolCoinPackage(arg1, arg2) {
  return window['go']['backend']['App']['InstallToolCoinPackage'](arg1, arg2);
}

export function InstallVCRedist() {
  return window['go']['backend']['App']['InstallVCRedist']();
}

export function KickPlayer(arg1, arg2) {
  return window['go']['backend']['App']['KickPlayer'](arg1, arg2);
}

export function LaunchToolCoin(arg1) {
  return window['go']['backend']['App']['LaunchToolCoin'](arg1);
}

export function ListAddons(arg1) {
  return window['go']['backend']['App']['ListAddons'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['backend']['App']['ListBackups'](arg1);
}

export function ListMods(arg1) {
  return window['go']['backend']['App']['ListMods'](arg1);
}

export function ListToolCoinDownloads(arg1) {
  return window['go']['backend']['App']['ListToolCoinDownloads'](arg1);
}

export function ListWorlds(arg1) {
  return window['go']['backend']['App']['ListWorlds'](arg1);
}

export function OpPlayer(arg1, arg2) {
  return window['go']['backend']['App']['OpPlayer'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['backend']['App']['OpenFolder'](arg1);
}

export function OpenToolCoinDownloadsFolder(arg1) {
  return window['go']['backend']['App']['OpenToolCoinDownloadsFolder'](arg1);
}

export function PollXboxDeviceAuth(arg1) {
  return window['go']['backend']['App']['PollXboxDeviceAuth'](arg1);
}

export function PruneBackups(arg1, arg2) {
  return window['go']['backend']['App']['PruneBackups'](arg1, arg2);
}

export function PurgeDownloadedCache() {
  return window['go']['backend']['App']['PurgeDownloadedCache']();
}

export function RefreshCurseForgeCatalog() {
  return window['go']['backend']['App']['RefreshCurseForgeCatalog']();
}

export function RefreshMarketplaceDefinitions() {
  return window['go']['backend']['App']['RefreshMarketplaceDefinitions']();
}

export function RemoveAllowlistPlayer(arg1, arg2) {
  return window['go']['backend']['App']['RemoveAllowlistPlayer'](arg1, arg2);
}

export function RemoveMod(arg1) {
  return window['go']['backend']['App']['RemoveMod'](arg1);
}

export function ReorderWorldPacks(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ReorderWorldPacks'](arg1, arg2, arg3, arg4);
}

export function RescanServer(arg1) {
  return window['go']['backend']['App']['RescanServer'](arg1);
}

export function RestartServer(arg1) {
  return window['go']['backend']['App']['RestartServer'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['backend']['App']['RestoreBackup'](arg1, arg2);
}

export function SaveAppSettings(arg1) {
  return window['go']['backend']['App']['SaveAppSettings'](arg1);
}

export function SaveModConfig(arg1, arg2) {
  return window['go']['backend']['App']['SaveModConfig'](arg1, arg2);
}

export function SaveServerProperties(arg1, arg2) {
  return window['go']['backend']['App']['SaveServerProperties'](arg1, arg2);
}

export function SaveWorldOptions(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveWorldOptions'](arg1, arg2, arg3);
}

export function SaveXboxAccount(arg1) {
  return window['go']['backend']['App']['SaveXboxAccount'](arg1);
}

export function ScanRecentCurseForgeDownloads() {
  return window['go']['backend']['App']['ScanRecentCurseForgeDownloads']();
}

export function SelectFileDialog(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SelectFileDialog'](arg1, arg2, arg3);
}

export function SelectFolderDialog() {
  return window['go']['backend']['App']['SelectFolderDialog']();
}

export function SendConsoleCommand(arg1, arg2) {
  return window['go']['backend']['App']['SendConsoleCommand'](arg1, arg2);
}

export function SetActiveServer(arg1) {
  return window['go']['backend']['App']['SetActiveServer'](arg1);
}

export function SetActiveWorld(arg1, arg2) {
  return window['go']['backend']['App']['SetActiveWorld'](arg1, arg2);
}

export function SetExtensionEnabled(arg1, arg2) {
  return window['go']['backend']['App']['SetExtensionEnabled'](arg1, arg2);
}

export function SetPlayerPermission(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SetPlayerPermission'](arg1, arg2, arg3);
}

export function SetPreference(arg1, arg2) {
  return window['go']['backend']['App']['SetPreference'](arg1, arg2);
}

export function SetServerMemoryLimit(arg1, arg2) {
  return window['go']['backend']['App']['SetServerMemoryLimit'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['backend']['App']['StartServer'](arg1);
}

export function StartXboxDeviceAuth() {
  return window['go']['backend']['App']['StartXboxDeviceAuth']();
}

export function StopServer(arg1) {
  return window['go']['backend']['App']['StopServer'](arg1);
}

export function SyncBedrinthCatalog() {
  return window['go']['backend']['App']['SyncBedrinthCatalog']();
}

export function ToggleAddonForWorld(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ToggleAddonForWorld'](arg1, arg2, arg3, arg4);
}

export function ToggleAllowlist(arg1, arg2) {
  return window['go']['backend']['App']['ToggleAllowlist'](arg1, arg2);
}

export function ToggleFullscreen() {
  return window['go']['backend']['App']['ToggleFullscreen']();
}

export function UnassignAddonFromWorld(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UnassignAddonFromWorld'](arg1, arg2, arg3, arg4);
}

export function UnbanPlayer(arg1, arg2) {
  return window['go']['backend']['App']['UnbanPlayer'](arg1, arg2);
}

export function UninstallAddon(arg1, arg2) {
  return window['go']['backend']['App']['UninstallAddon'](arg1, arg2);
}

export function UninstallBedrinthPackage(arg1, arg2) {
  return window['go']['backend']['App']['UninstallBedrinthPackage'](arg1, arg2);
}

export function UninstallExtension(arg1) {
  return window['go']['backend']['App']['UninstallExtension'](arg1);
}

export function UpdateLipPackage(arg1, arg2) {
  return window['go']['backend']['App']['UpdateLipPackage'](arg1, arg2);
}

export function WipeEverything(arg1) {
  return window['go']['backend']['App']['WipeEverything'](arg1);
}
